In [137]:
from idlelib.iomenu import errors

import pandas as pd

In [139]:
# data = pd.read_excel("sales_raw_500.xlsx")
# data
data = pd.read_csv("sales_raw_new_2026.csv")
data

     Order_ID  Order_Date Customer Region  Product  Sales   Cost
0        2001  2026-01-21     Neha   West   Laptop  16494  13135
1        2002  2026-01-07   Anjali  North  Monitor  35140  19722
2        2003  2026-01-28    Vikas  North   Mobile  18889  13511
3        2004  2026-01-04    Kiran  North   Mobile  89657  66187
4        2005  2026-03-02    Rahul   West   Laptop  35977  20290
..        ...         ...      ...    ...      ...    ...    ...
195      2196  2026-01-26    Kiran   East  Printer  28305  16671
196      2197  2026-01-04   Suresh  South  Printer  18669  13476
197      2198  2026-03-01   Anjali  South   Mobile  52605  33403
198      2199  2026-02-03     Neha  North   Laptop  57296  39944
199      2200  2026-02-21    Priya   East   Mobile  12701  10702

[200 rows x 7 columns]

In [102]:
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    520 non-null    int64
 1   Order_Date  502 non-null    datetime64[us]
 2   Customer    520 non-null    str
 3   Region      520 non-null    str
 4   Product     520 non-null    str
 5   Sales       520 non-null    int64
 6   Cost        520 non-null    int64
dtypes: datetime64[us](1), int64(3), str(3)
memory usage: 36.6 KB
None

In [103]:
print(data.describe())

          Order_ID                  Order_Date         Sales          Cost
count   520.000000                         502    520.000000    520.000000
mean   1250.867308  2023-08-18 09:36:34.422310  41129.607692  30675.001923
min    1001.000000         2023-01-04 00:00:00   5205.000000   3272.000000
25%    1124.750000         2023-05-03 00:00:00  22015.750000  16388.000000
50%    1251.500000         2023-08-15 00:00:00  41044.000000  30349.000000
75%    1377.250000         2023-12-12 00:00:00  59245.000000  43363.500000
max    1500.000000         2024-03-26 00:00:00  79928.000000  71417.000000
std     145.030140                         NaN  21605.117122  16598.086873

In [150]:
# data= data.isnull()
# data
data = data.drop_duplicates()
data

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,profit,year,Month
0,2001,2026-01-21,Neha,West,Laptop,16494,13135,3359,2026,1
1,2002,2026-01-07,Anjali,North,Monitor,35140,19722,15418,2026,1
2,2003,2026-01-28,Vikas,North,Mobile,18889,13511,5378,2026,1
3,2004,2026-01-04,Kiran,North,Mobile,89657,66187,23470,2026,1
4,2005,2026-03-02,Rahul,West,Laptop,35977,20290,15687,2026,3
...,...,...,...,...,...,...,...,...,...,...
195,2196,2026-01-26,Kiran,East,Printer,28305,16671,11634,2026,1
196,2197,2026-01-04,Suresh,South,Printer,18669,13476,5193,2026,1
197,2198,2026-03-01,Anjali,South,Mobile,52605,33403,19202,2026,3
198,2199,2026-02-03,Neha,North,Laptop,57296,39944,17352,2026,2
199,2200,2026-02-21,Priya,East,Mobile,12701,10702,1999,2026,2

     Order_ID  Order_Date  Customer  Region  Product  Sales   Cost
0       False       False     False   False    False  False  False
1       False       False     False   False    False  False  False
2       False       False     False   False    False  False  False
3       False       False     False   False    False  False  False
4       False       False     False   False    False  False  False
..        ...         ...       ...     ...      ...    ...    ...
515     False       False     False   False    False  False  False
516     False       False     False   False    False  False  False
517     False       False     False   False    False  False  False
518     False       False     False   False    False  False  False
519     False       False     False   False    False  False  False

[520 rows x 7 columns]

In [140]:
# Standard fix
data['Order_Date'] = pd.to_datetime(data['Order_Date'], errors='coerce')

In [141]:
data = data.dropna(subset=['Order_Date'])

In [142]:
data

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        2001 2026-01-21     Neha   West   Laptop  16494  13135
1        2002 2026-01-07   Anjali  North  Monitor  35140  19722
2        2003 2026-01-28    Vikas  North   Mobile  18889  13511
3        2004 2026-01-04    Kiran  North   Mobile  89657  66187
4        2005 2026-03-02    Rahul   West   Laptop  35977  20290
..        ...        ...      ...    ...      ...    ...    ...
195      2196 2026-01-26    Kiran   East  Printer  28305  16671
196      2197 2026-01-04   Suresh  South  Printer  18669  13476
197      2198 2026-03-01   Anjali  South   Mobile  52605  33403
198      2199 2026-02-03     Neha  North   Laptop  57296  39944
199      2200 2026-02-21    Priya   East   Mobile  12701  10702

[200 rows x 7 columns]

In [143]:
# profit
# sales-cost
data['profit']= data['Sales']- data["Cost"]

In [144]:
# year column
data['year']= data['Order_Date'].dt.year

In [145]:
# Month Column
data['Month']= data['Order_Date'].dt.month

In [146]:
print(data)

     Order_ID Order_Date Customer Region  Product  Sales   Cost  profit  year  \
0        2001 2026-01-21     Neha   West   Laptop  16494  13135    3359  2026
1        2002 2026-01-07   Anjali  North  Monitor  35140  19722   15418  2026
2        2003 2026-01-28    Vikas  North   Mobile  18889  13511    5378  2026
3        2004 2026-01-04    Kiran  North   Mobile  89657  66187   23470  2026
4        2005 2026-03-02    Rahul   West   Laptop  35977  20290   15687  2026
..        ...        ...      ...    ...      ...    ...    ...     ...   ...
195      2196 2026-01-26    Kiran   East  Printer  28305  16671   11634  2026
196      2197 2026-01-04   Suresh  South  Printer  18669  13476    5193  2026
197      2198 2026-03-01   Anjali  South   Mobile  52605  33403   19202  2026
198      2199 2026-02-03     Neha  North   Laptop  57296  39944   17352  2026
199      2200 2026-02-21    Priya   East   Mobile  12701  10702    1999  2026

     Month
0        1
1        1
2        1
3        1
4        3
..     ...
195      1
196      1
197      3
198      2
199      2

[200 rows x 10 columns]

In [131]:
data.to_csv('sales_cleaned.csv', index=False)

In [ ]:
# data python + Excel+ Sql

In [147]:
import pandas as pd
from sqlalchemy import create_engine

In [133]:
data = pd.read_csv('sales_cleaned.csv')

data

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,profit,year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
477,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
478,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
479,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
480,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
481,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [148]:
# engine
engine = create_engine('mysql+pymysql://root:Nitin%404052@localhost:3306/saledb')

In [149]:
# insert data into sql
# data.to_sql(name='sales_data',con=engine,if_exists='replace',index=False )

data.to_sql(name='sales_data',con=engine,if_exists='append',index=False )

200

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,profit,year,Month
0,2001,2026-01-21,Neha,West,Laptop,16494,13135,3359,2026,1
1,2002,2026-01-07,Anjali,North,Monitor,35140,19722,15418,2026,1
2,2003,2026-01-28,Vikas,North,Mobile,18889,13511,5378,2026,1
3,2004,2026-01-04,Kiran,North,Mobile,89657,66187,23470,2026,1
4,2005,2026-03-02,Rahul,West,Laptop,35977,20290,15687,2026,3
...,...,...,...,...,...,...,...,...,...,...
195,2196,2026-01-26,Kiran,East,Printer,28305,16671,11634,2026,1
196,2197,2026-01-04,Suresh,South,Printer,18669,13476,5193,2026,1
197,2198,2026-03-01,Anjali,South,Mobile,52605,33403,19202,2026,3
198,2199,2026-02-03,Neha,North,Laptop,57296,39944,17352,2026,2
199,2200,2026-02-21,Priya,East,Mobile,12701,10702,1999,2026,2